<a href="https://colab.research.google.com/github/Julian-Ramirez-M/Talleres/blob/main/Taller_2_Juliana_Prado_y_Juli%C3%A1n_Ram%C3%ADrez.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
import cvxpy as cp
import matplotlib.pyplot as plt
from scipy.optimize import minimize
from scipy.optimize import linprog

**1 Punto**

In [2]:
df = pd.DataFrame({"": ["Materia prima", "Mano de obra", "capital $", "Ganancia"],
                   "Producto A" : [1, 2, 1, 3],
                   "Producto B" : [1, 4, 2, 4]})
df

                  Producto A  Producto B
0  Materia prima           1           1
1   Mano de obra           2           4
2      capital $           1           2
3       Ganancia           3           4

In [3]:
c = np.array([3, 5])
A = np.array([[1,1],
              [2,4],
              [1,2]])
b = np.array ([500,1000,2000])
lim = [(100, None),
       (150, None)]
sol = linprog(-c, A_ub=A, b_ub=b, bounds=lim, method="revised simplex")
sol.x

<ipython-input-3-6b3ea4dd6701>:8: DeprecationWarning: `method='revised simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  sol = linprog(-c, A_ub=A, b_ub=b, bounds=lim, method="revised simplex")

array([200., 150.])

**2 Punto**

In [4]:
#SCIPY
c2 = np.array([0.10, 0.15, 0.16, 0.08])
res1 = np.array([[0.5, 0.3, 0.25, 0.6],
                 [0.3, 0.1, 0.4, 0.2],
                 [0.2, 0.6, 0.35, 0.2]])
res2 = np.array([0.35, 0.30, 0.15])
res3 = np.array([[1,1,1,1]])
res4 = np.array([1])
r = linprog(-c2, A_ub=-res1, b_ub=-res2, A_eq=res3, b_eq=res4, method="simplex")
pd.DataFrame(r.x).round(4).T

<ipython-input-4-8596af18be1e>:9: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  r = linprog(-c2, A_ub=-res1, b_ub=-res2, A_eq=res3, b_eq=res4, method="simplex")

     0       1       2       3
0  0.0  0.1579  0.5789  0.2632

In [5]:
#CVXPY
n = 4
x = cp.Variable(n)
obj = cp.Minimize(-c2.T@x)
cons = [cp.sum(x)==1,res1@x>=res2,x>=0]
prob = cp.Problem(obj,cons)
Ans2 = prob.solve()
ans_2 = pd.DataFrame(x.value)
pd.DataFrame(ans_2).round(4).T

     0       1       2       3
0  0.0  0.1579  0.5789  0.2632

**3 Punto**

In [6]:
c3 = np.array([0,0,0,0,0,0,0,0,0,0,0,0,0,1])
A3 = np.array([[1,0,0,0,0,1,0,0,-1,0,0,0,0,0],
               [-1.01,1,0,0,0,0,1,0,1.003,-1,0,0,0,0],
               [0,-1.01,1,0,0,0,0,1,0,1.003,-1,0,0,0],
               [0,0,-1.01,1,0,-1.02,0,0,0,0,1.003,-1,0,0],
               [0,0,0,-1.01,1,0,-1.02,0,0,0,0,1.003,-1,0],
               [0,0,0,0,-1.01,0,0,-1.02,0,0,0,0,1.003,-1]])
b3 = np.array([150,100,-200,200,-50,-300])
Ans3 = linprog(-c3, A_eq=A3, b_eq=b3, method="simplex")
pd.DataFrame(Ans3.x).T

<ipython-input-6-67f7633e7f68>:9: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  Ans3 = linprog(-c3, A_eq=A3, b_eq=b3, method="simplex")

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,0.0,50.980392,0.0,0.0,0.0,150.0,49.019608,203.434364,0.0,0.0,351.944167,0.0,0.0,92.496949

In [20]:
n3 = 14
x3 = cp.Variable(n3)
Obj3 = cp.Minimize(-c3@x3)
cons3 = [A3@x3==b3,x3>=0]
prob3 =cp.Problem(Obj3,cons3)
Result = prob3.solve(solver=cp.GLPK_MI)
x_sol3=pd.DataFrame(x3.value)
pd.DataFrame(x_sol3).round(2).T

,0,1,2,3,4,5,6,7,8,9,10,11,12,13
0,-0.0,50.98,-0.0,-0.0,-0.0,150.0,49.02,203.43,-0.0,-0.0,351.94,-0.0,-0.0,92.5

**4 Punto**

In [9]:
c4 = np.array([0,0,0,0,0,0,0,1])
rest4 = (1+0.0001)**7
A4 = np.array([[1,0,0,0,-1,0,0,0],
               [0,1,0,0,rest4,-1,0,0],
               [0,0,1,0,0,rest4,-1,0],
               [0,0,0,1,0,0,rest4,-1]])
b4 = np.array([[150,-100,-50,200]])
r4 = linprog(-c4, A_ub=A4, b_ub=-b4, method="simplex")
Ans4 = pd.DataFrame(r4.x).T
Ans4

<ipython-input-9-f2c0d72e429b>:8: DeprecationWarning: `method='simplex'` is deprecated and will be removed in SciPy 1.11.0. Please use one of the HiGHS solvers (e.g. `method='highs'`) in new code.
  r4 = linprog(-c4, A_ub=A4, b_ub=-b4, method="simplex")

     0    1    2    3      4          5         6           7
0  0.0  0.0  0.0  0.0  150.0  50.105032  0.140116  200.140214

**5 Punto**

In [10]:
c5 = np.array([0,0,0,5,8,10])
A5 = np.array([[0,0,0,1,0,0],
               [0,1,0,0,0,0],
               [0,0,1,0,0,0],
               [0,0,0,0,1,0],
               [0,0,0,0,0,1]])
b5 = np.array([2000,300,250,2000,2000])
Aeq5 = np.array([[1,1,1,0,0,0],
                 [0,0,0,1,1,1]])
beq5 = np.array([1000,10000])
r5 = linprog(-c5, A_ub=-A5, b_ub= -b5, A_eq= Aeq5, b_eq= beq5)
Ans5 = pd.DataFrame(r5.x).T
Ans5

       0      1      2       3       4       5
0  450.0  300.0  250.0  2000.0  2000.0  6000.0

**6 Punto**

In [11]:
c6 = np.array([[4,5,6,8,10],
       [6,4,3,5,8],
       [9,7,4,3,4]])
b6 = np.array([500,500,500])
f = np.array([1000,1000,1000])
b6_2 = np.array([80,270,250,160,180])
x = cp.Variable((3,5),nonneg=True)
y = cp.Variable(3,boolean=True)
obj = cp.Minimize(cp.sum(cp.multiply(c6,x))+cp.sum(cp.multiply(f,y)))
rest = [cp.sum(x[0,:])<=500*y[0],cp.sum(x[1,:])<=500*y[1],cp.sum(x[2,:])<=500*y[2],cp.sum(x[:,0])==b6_2[0],
        cp.sum(x[:,1])==b6_2[1],cp.sum(x[:,2])==b6_2[2],cp.sum(x[:,3])==b6_2[3],
        cp.sum(x[:,4])==b6_2[4],cp.sum(y)==2]
pro = cp.Problem(obj,rest)
Ans6 = pro.solve()
x_Ans6 = pd.DataFrame(x.value)
pd.DataFrame(x_Ans6).round(2)

      0      1      2      3      4
0  -0.0   -0.0   -0.0   -0.0   -0.0
1  80.0  270.0  150.0   -0.0   -0.0
2  -0.0   -0.0  100.0  160.0  180.0